trigger:
- master

pool:
  # Agent VM image name
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
  
    steps:
     - task: Maven@3
       displayName: 'Maven Package'
       inputs:
        mavenPomFile: 'pom.xml'

     - task: CopyFiles@2
       displayName: 'Copy Files to artifact staging directory'
       inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

     - publish: $(Build.ArtifactStagingDirectory)
       artifact: books
     #- upload: $(System.DefaultWorkingDirectory)
      # artifact: application
      
